package seeder

import "lectronic/src/databases/orm/models"

var ProductSeed = models.Products{
	{
		Name:        "Beyerdynamic DT 990 Pro",
		Description: "The Beyerdynamic DT 990 Pro features open-back design, 250 ohm impedance, and a frequency response of 5 Hz - 35 kHz.Dolor in aute Lorem velit eu.Minim id consequat quis qui consectetur aliqua deserunt tempor consequat nostrud labore nisi.Magna ut aliqua labore in nulla.Aute nisi labore aliquip dolor.Deserunt et ea aliqua labore cillum ullamco non veniam occaecat nisi.Ut proident cillum nostrud velit sunt culpa culpa magna aute commodo cupidatat elit.Commodo tempor exercitation in nostrud est occaecat et fugiat consectetur sunt.Sit laborum velit irure deserunt ipsum in anim velit esse esse ea.Excepteur reprehenderit aute consectetur mollit do consequat ea nisi nulla deserunt adipisicing pariatur.Commodo in nisi elit ullamco pariatur adipisicing enim adipisicing sunt ut fugiat non aute eu.Deserunt occaecat laborum occaecat fugiat qui proident quis adipisicing proident nisi consectetur laboris.Anim officia officia ea laborum consectetur fugiat fugiat.Dolore consectetur adipisicing eiusmod voluptate.Nostrud ipsum sunt ipsum irure irure incididunt sunt nisi laboris.Aliqua sit sunt aliqua et adipisicing ut dolor culpa irure irure duis.",
		Price:       3699000,
		Category:    "Handphone",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106070/lectronic/1678106069252305300.png",
		Stock:       6,
	},
	{
		Name:        "Sennheiser HD 660 S",
		Description: "The Sennheiser HD 660 S features open-back design, 150 ohm impedance, and a frequency response of 10 Hz - 41 kHz.Mollit labore ad aute dolore est nisi in.Labore amet laborum ex ex incididunt sunt cupidatat adipisicing minim ad cillum exercitation.Consectetur eiusmod ipsum laborum anim cillum nulla labore cupidatat velit pariatur.Eu est reprehenderit ut dolor nostrud enim consequat esse.Eiusmod fugiat nulla officia magna.Anim in velit sunt consectetur cupidatat aliquip exercitation anim irure nostrud.Qui id exercitation consectetur nisi nisi.Aliqua ex cillum ea reprehenderit tempor duis sunt fugiat.Amet quis nulla sint et aute magna velit nulla.Excepteur est mollit deserunt cupidatat quis.In ipsum non non irure tempor aliquip qui id ex Lorem adipisicing.Ea ipsum tempor nulla deserunt exercitation nostrud excepteur exercitation.Sint sunt elit labore fugiat non fugiat nostrud adipisicing consectetur proident consequat.Laboris cupidatat quis anim mollit qui.Aliquip officia aliqua ex laborum deserunt nisi commodo sit ipsum ea.",
		Price:       7899000,
		Category:    "Handphone",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106063/lectronic/1678106062371155900.png",
		Stock:       3,
	},
	{
		Name:        "Audio-Technica ATH-M50x",
		Description: "The Audio-Technica ATH-M50x features closed-back design, 45mm drivers, and a frequency response of 15 Hz - 28 kHz.Laboris irure occaecat dolor sint consequat.Fugiat sit ex aliquip irure aliquip ut sint cillum qui amet fugiat.Id magna exercitation reprehenderit aute exercitation adipisicing duis.Voluptate officia incididunt voluptate do cupidatat.Tempor sunt dolore sint ipsum dolor laborum ullamco esse tempor aute minim.Deserunt excepteur magna laboris veniam in quis.Cupidatat consequat elit anim voluptate deserunt consequat sunt.Reprehenderit ullamco consectetur exercitation voluptate ex pariatur esse in fugiat ea anim aute.Sint duis cupidatat adipisicing excepteur id veniam.Quis aute nulla voluptate consequat occaecat.Velit esse do ut magna proident cillum enim enim duis non ea.Cillum adipisicing culpa adipisicing amet ut sunt adipisicing elit anim laborum sit anim aliquip nostrud.Fugiat nulla cupidatat dolor ex pariatur laborum laboris do voluptate incididunt culpa deserunt.Id dolore adipisicing nisi et aliqua adipisicing.Magna voluptate laborum ad ex voluptate.Sit ullamco occaecat occaecat qui nostrud veniam nisi excepteur proident non.Ipsum tempor incididunt ipsum ea cillum consectetur laboris labore laboris excepteur.Dolor tempor in laboris commodo ea reprehenderit magna officia ut labore amet ad.Amet ipsum laboris nisi commodo nulla deserunt ut consequat.",
		Price:       2999000,
		Category:    "Handphone",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106076/lectronic/1678106075119276400.png",
		Stock:       3,
	},
	{
		Name:        "Beyerdynamic DT 990 Pro",
		Description: "The Beyerdynamic DT 990 Pro features open-back design, 250 ohm impedance, and a frequency response of 5 Hz - 35 kHz.Dolor in aute Lorem velit eu.Minim id consequat quis qui consectetur aliqua deserunt tempor consequat nostrud labore nisi.Magna ut aliqua labore in nulla.Aute nisi labore aliquip dolor.Deserunt et ea aliqua labore cillum ullamco non veniam occaecat nisi.Ut proident cillum nostrud velit sunt culpa culpa magna aute commodo cupidatat elit.Commodo tempor exercitation in nostrud est occaecat et fugiat consectetur sunt.Sit laborum velit irure deserunt ipsum in anim velit esse esse ea.Excepteur reprehenderit aute consectetur mollit do consequat ea nisi nulla deserunt adipisicing pariatur.Commodo in nisi elit ullamco pariatur adipisicing enim adipisicing sunt ut fugiat non aute eu.Deserunt occaecat laborum occaecat fugiat qui proident quis adipisicing proident nisi consectetur laboris.Anim officia officia ea laborum consectetur fugiat fugiat.Dolore consectetur adipisicing eiusmod voluptate.Nostrud ipsum sunt ipsum irure irure incididunt sunt nisi laboris.Aliqua sit sunt aliqua et adipisicing ut dolor culpa irure irure duis.",
		Price:       3699000,
		Category:    "Handphone",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106070/lectronic/1678106069252305300.png",
		Stock:       6,
	},
	{
		Name:        "Sennheiser HD 660 S",
		Description: "The Sennheiser HD 660 S features open-back design, 150 ohm impedance, and a frequency response of 10 Hz - 41 kHz.Mollit labore ad aute dolore est nisi in.Labore amet laborum ex ex incididunt sunt cupidatat adipisicing minim ad cillum exercitation.Consectetur eiusmod ipsum laborum anim cillum nulla labore cupidatat velit pariatur.Eu est reprehenderit ut dolor nostrud enim consequat esse.Eiusmod fugiat nulla officia magna.Anim in velit sunt consectetur cupidatat aliquip exercitation anim irure nostrud.Qui id exercitation consectetur nisi nisi.Aliqua ex cillum ea reprehenderit tempor duis sunt fugiat.Amet quis nulla sint et aute magna velit nulla.Excepteur est mollit deserunt cupidatat quis.In ipsum non non irure tempor aliquip qui id ex Lorem adipisicing.Ea ipsum tempor nulla deserunt exercitation nostrud excepteur exercitation.Sint sunt elit labore fugiat non fugiat nostrud adipisicing consectetur proident consequat.Laboris cupidatat quis anim mollit qui.Aliquip officia aliqua ex laborum deserunt nisi commodo sit ipsum ea.",
		Price:       7899000,
		Category:    "AirConditioner",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106063/lectronic/1678106062371155900.png",
		Stock:       3,
	},
	{
		Name:        "Audio-Technica ATH-M50x",
		Description: "The Audio-Technica ATH-M50x features closed-back design, 45mm drivers, and a frequency response of 15 Hz - 28 kHz.Laboris irure occaecat dolor sint consequat.Fugiat sit ex aliquip irure aliquip ut sint cillum qui amet fugiat.Id magna exercitation reprehenderit aute exercitation adipisicing duis.Voluptate officia incididunt voluptate do cupidatat.Tempor sunt dolore sint ipsum dolor laborum ullamco esse tempor aute minim.Deserunt excepteur magna laboris veniam in quis.Cupidatat consequat elit anim voluptate deserunt consequat sunt.Reprehenderit ullamco consectetur exercitation voluptate ex pariatur esse in fugiat ea anim aute.Sint duis cupidatat adipisicing excepteur id veniam.Quis aute nulla voluptate consequat occaecat.Velit esse do ut magna proident cillum enim enim duis non ea.Cillum adipisicing culpa adipisicing amet ut sunt adipisicing elit anim laborum sit anim aliquip nostrud.Fugiat nulla cupidatat dolor ex pariatur laborum laboris do voluptate incididunt culpa deserunt.Id dolore adipisicing nisi et aliqua adipisicing.Magna voluptate laborum ad ex voluptate.Sit ullamco occaecat occaecat qui nostrud veniam nisi excepteur proident non.Ipsum tempor incididunt ipsum ea cillum consectetur laboris labore laboris excepteur.Dolor tempor in laboris commodo ea reprehenderit magna officia ut labore amet ad.Amet ipsum laboris nisi commodo nulla deserunt ut consequat.",
		Price:       2999000,
		Category:    "AirConditioner",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106076/lectronic/1678106075119276400.png",
		Stock:       3,
	},
	{
		Name:        "Bose QuietComfort 35 II",
		Description: "The Bose QuietComfort 35 II features noise-cancellation technology, up to 20 hours of battery life, and Alexa voice control. Aliqua anim id veniam aute do culpa.Sunt occaecat excepteur dolor ea do ullamco.Aute cupidatat eu magna deserunt incididunt do incididunt dolore labore qui commodo aliqua officia eiusmod.Exercitation incididunt aliquip dolore laborum occaecat nostrud mollit laboris non consectetur dolor veniam.Et anim ut ea pariatur officia pariatur adipisicing eu.Ipsum id aliqua veniam laboris consectetur exercitation magna amet mollit reprehenderit velit amet.Officia Lorem labore sit nulla mollit nisi enim non culpa velit.Id et nostrud pariatur mollit ipsum et.Ipsum ipsum ipsum ipsum deserunt irure non adipisicing qui sint enim commodo nisi sit labore.Adipisicing ad velit minim commodo adipisicing amet Lorem mollit esse.Proident do nostrud cupidatat anim incididunt.Ipsum occaecat adipisicing anim velit.Pariatur do in non ad velit anim adipisicing ea nulla.Do consectetur esse proident exercitation adipisicing laborum Lorem dolore velit cupidatat in ea aute.Id aliquip ad excepteur proident labore minim ipsum adipisicing.Consequat do adipisicing proident sit mollit.Non fugiat sunt laboris Lorem sit exercitation consequat ex Lorem ut.Commodo officia sit ad consequat deserunt ut sit.Ullamco eiusmod cillum dolore excepteur quis id ea aliqua ut est exercitation cupidatat elit aliquip.Amet voluptate exercitation reprehenderit occaecat aute Lorem.",
		Price:       3499000,
		Category:    "AirConditioner",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106070/lectronic/1678106069252305300.png",
		Stock:       15,
	},
	{
		Name:        "Sony WH-1000XM4",
		Description: "The Sony WH-1000XM4 features noise-cancellation technology, 30 hours of battery life, and support for LDAC audio.Amet sit occaecat velit adipisicing sit eu tempor officia laborum fugiat dolor.Non sit Lorem commodo veniam do sunt labore consequat ipsum officia pariatur sunt culpa.Nostrud do deserunt velit sit est deserunt aute.Sint sunt laborum ex esse eu.Amet nostrud sit sit magna sint ullamco nostrud.Anim deserunt occaecat ipsum consectetur veniam aliqua do laborum velit exercitation.Nostrud irure irure est quis tempor culpa officia deserunt.Ex proident deserunt commodo adipisicing esse pariatur nisi laboris.Nostrud id est culpa ipsum sint deserunt ex dolore.Velit officia sint consectetur consequat quis qui.Ipsum incididunt incididunt et amet voluptate laboris sint eiusmod velit nostrud ullamco.Nostrud eiusmod elit commodo adipisicing.Veniam culpa dolor nulla consequat commodo nulla ex eu labore Lorem qui.Adipisicing proident fugiat voluptate eiusmod amet occaecat et pariatur officia.Irure exercitation excepteur labore eu dolor ex qui sint.Mollit ex officia et culpa consectetur Lorem ut pariatur dolore ad adipisicing do.Aliquip amet aute proident consectetur et eu minim est quis nulla.",
		Price:       4299000,
		Category:    "AirConditioner",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106063/lectronic/1678106062371155900.png",
		Stock:       9,
	},
	{
		Name:        "Jabra Elite 85t",
		Description: "The Jabra Elite 85t features active noise-cancellation, up to 25 hours of battery life, and customizable equalizer settings.Elit mollit cupidatat adipisicing excepteur velit minim pariatur et.Nostrud in ipsum incididunt nisi ut minim est velit irure fugiat quis.Ullamco velit consequat sint cupidatat dolore aliquip excepteur nisi.Minim amet sunt aliquip et est ea eiusmod reprehenderit ullamco.Sunt labore enim dolore amet tempor esse.Do velit ullamco eiusmod tempor ullamco sint.Aliqua ex veniam irure sint adipisicing aute exercitation est est proident veniam.Quis id quis nulla dolore.Laborum nostrud ex non nulla est elit quis ut sunt quis do ad.Nulla incididunt proident ex proident pariatur non dolore ullamco ipsum Lorem. Pariatur aliquip sit elit minim cupidatat magna officia.Dolor pariatur magna id do.Consequat aliqua consequat officia eiusmod anim est minim pariatur magna ad.Excepteur ut aute ipsum culpa sit laborum cupidatat cillum esse.Quis qui dolore nulla laborum.Nulla ea Lorem laboris ea exercitation irure commodo sit elit irure amet laborum velit.Ea id adipisicing ad Lorem ex in exercitation commodo nulla dolor consequat aute enim labore.Qui proident minim occaecat deserunt amet id ex minim voluptate qui.Eiusmod deserunt exercitation esse Lorem do.Ea nisi minim fugiat consectetur ut fugiat voluptate.Culpa irure cupidatat dolore cillum.Laboris nulla irure minim reprehenderit Lorem deserunt.Proident cupidatat non elit cupidatat officia dolor nulla officia culpa fugiat nulla.",
		Price:       2999000,
		Category:    "Television",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106076/lectronic/1678106075119276400.png",
		Stock:       12,
	},
	{
		Name:        "Beyerdynamic DT 990 Pro",
		Description: "The Beyerdynamic DT 990 Pro features open-back design, 250 ohm impedance, and a frequency response of 5 Hz - 35 kHz.Dolor in aute Lorem velit eu.Minim id consequat quis qui consectetur aliqua deserunt tempor consequat nostrud labore nisi.Magna ut aliqua labore in nulla.Aute nisi labore aliquip dolor.Deserunt et ea aliqua labore cillum ullamco non veniam occaecat nisi.Ut proident cillum nostrud velit sunt culpa culpa magna aute commodo cupidatat elit.Commodo tempor exercitation in nostrud est occaecat et fugiat consectetur sunt.Sit laborum velit irure deserunt ipsum in anim velit esse esse ea.Excepteur reprehenderit aute consectetur mollit do consequat ea nisi nulla deserunt adipisicing pariatur.Commodo in nisi elit ullamco pariatur adipisicing enim adipisicing sunt ut fugiat non aute eu.Deserunt occaecat laborum occaecat fugiat qui proident quis adipisicing proident nisi consectetur laboris.Anim officia officia ea laborum consectetur fugiat fugiat.Dolore consectetur adipisicing eiusmod voluptate.Nostrud ipsum sunt ipsum irure irure incididunt sunt nisi laboris.Aliqua sit sunt aliqua et adipisicing ut dolor culpa irure irure duis.",
		Price:       3699000,
		Category:    "Television",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106070/lectronic/1678106069252305300.png",
		Stock:       6,
	},
	{
		Name:        "Sennheiser HD 660 S",
		Description: "The Sennheiser HD 660 S features open-back design, 150 ohm impedance, and a frequency response of 10 Hz - 41 kHz.Mollit labore ad aute dolore est nisi in.Labore amet laborum ex ex incididunt sunt cupidatat adipisicing minim ad cillum exercitation.Consectetur eiusmod ipsum laborum anim cillum nulla labore cupidatat velit pariatur.Eu est reprehenderit ut dolor nostrud enim consequat esse.Eiusmod fugiat nulla officia magna.Anim in velit sunt consectetur cupidatat aliquip exercitation anim irure nostrud.Qui id exercitation consectetur nisi nisi.Aliqua ex cillum ea reprehenderit tempor duis sunt fugiat.Amet quis nulla sint et aute magna velit nulla.Excepteur est mollit deserunt cupidatat quis.In ipsum non non irure tempor aliquip qui id ex Lorem adipisicing.Ea ipsum tempor nulla deserunt exercitation nostrud excepteur exercitation.Sint sunt elit labore fugiat non fugiat nostrud adipisicing consectetur proident consequat.Laboris cupidatat quis anim mollit qui.Aliquip officia aliqua ex laborum deserunt nisi commodo sit ipsum ea.",
		Price:       7899000,
		Category:    "Television",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106063/lectronic/1678106062371155900.png",
		Stock:       3,
	},
	{
		Name:        "Audio-Technica ATH-M50x",
		Description: "The Audio-Technica ATH-M50x features closed-back design, 45mm drivers, and a frequency response of 15 Hz - 28 kHz.Laboris irure occaecat dolor sint consequat.Fugiat sit ex aliquip irure aliquip ut sint cillum qui amet fugiat.Id magna exercitation reprehenderit aute exercitation adipisicing duis.Voluptate officia incididunt voluptate do cupidatat.Tempor sunt dolore sint ipsum dolor laborum ullamco esse tempor aute minim.Deserunt excepteur magna laboris veniam in quis.Cupidatat consequat elit anim voluptate deserunt consequat sunt.Reprehenderit ullamco consectetur exercitation voluptate ex pariatur esse in fugiat ea anim aute.Sint duis cupidatat adipisicing excepteur id veniam.Quis aute nulla voluptate consequat occaecat.Velit esse do ut magna proident cillum enim enim duis non ea.Cillum adipisicing culpa adipisicing amet ut sunt adipisicing elit anim laborum sit anim aliquip nostrud.Fugiat nulla cupidatat dolor ex pariatur laborum laboris do voluptate incididunt culpa deserunt.Id dolore adipisicing nisi et aliqua adipisicing.Magna voluptate laborum ad ex voluptate.Sit ullamco occaecat occaecat qui nostrud veniam nisi excepteur proident non.Ipsum tempor incididunt ipsum ea cillum consectetur laboris labore laboris excepteur.Dolor tempor in laboris commodo ea reprehenderit magna officia ut labore amet ad.Amet ipsum laboris nisi commodo nulla deserunt ut consequat.",
		Price:       2999000,
		Category:    "Television",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106076/lectronic/1678106075119276400.png",
		Stock:       3,
	},
	{
		Name:        "Beyerdynamic DT 990 Pro",
		Description: "The Beyerdynamic DT 990 Pro features open-back design, 250 ohm impedance, and a frequency response of 5 Hz - 35 kHz.Dolor in aute Lorem velit eu.Minim id consequat quis qui consectetur aliqua deserunt tempor consequat nostrud labore nisi.Magna ut aliqua labore in nulla.Aute nisi labore aliquip dolor.Deserunt et ea aliqua labore cillum ullamco non veniam occaecat nisi.Ut proident cillum nostrud velit sunt culpa culpa magna aute commodo cupidatat elit.Commodo tempor exercitation in nostrud est occaecat et fugiat consectetur sunt.Sit laborum velit irure deserunt ipsum in anim velit esse esse ea.Excepteur reprehenderit aute consectetur mollit do consequat ea nisi nulla deserunt adipisicing pariatur.Commodo in nisi elit ullamco pariatur adipisicing enim adipisicing sunt ut fugiat non aute eu.Deserunt occaecat laborum occaecat fugiat qui proident quis adipisicing proident nisi consectetur laboris.Anim officia officia ea laborum consectetur fugiat fugiat.Dolore consectetur adipisicing eiusmod voluptate.Nostrud ipsum sunt ipsum irure irure incididunt sunt nisi laboris.Aliqua sit sunt aliqua et adipisicing ut dolor culpa irure irure duis.",
		Price:       3699000,
		Category:    "Router",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106070/lectronic/1678106069252305300.png",
		Stock:       6,
	},
	{
		Name:        "Sennheiser HD 660 S",
		Description: "The Sennheiser HD 660 S features open-back design, 150 ohm impedance, and a frequency response of 10 Hz - 41 kHz.Mollit labore ad aute dolore est nisi in.Labore amet laborum ex ex incididunt sunt cupidatat adipisicing minim ad cillum exercitation.Consectetur eiusmod ipsum laborum anim cillum nulla labore cupidatat velit pariatur.Eu est reprehenderit ut dolor nostrud enim consequat esse.Eiusmod fugiat nulla officia magna.Anim in velit sunt consectetur cupidatat aliquip exercitation anim irure nostrud.Qui id exercitation consectetur nisi nisi.Aliqua ex cillum ea reprehenderit tempor duis sunt fugiat.Amet quis nulla sint et aute magna velit nulla.Excepteur est mollit deserunt cupidatat quis.In ipsum non non irure tempor aliquip qui id ex Lorem adipisicing.Ea ipsum tempor nulla deserunt exercitation nostrud excepteur exercitation.Sint sunt elit labore fugiat non fugiat nostrud adipisicing consectetur proident consequat.Laboris cupidatat quis anim mollit qui.Aliquip officia aliqua ex laborum deserunt nisi commodo sit ipsum ea.",
		Price:       7899000,
		Category:    "Router",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106063/lectronic/1678106062371155900.png",
		Stock:       3,
	},
	{
		Name:        "Audio-Technica ATH-M50x",
		Description: "The Audio-Technica ATH-M50x features closed-back design, 45mm drivers, and a frequency response of 15 Hz - 28 kHz.Laboris irure occaecat dolor sint consequat.Fugiat sit ex aliquip irure aliquip ut sint cillum qui amet fugiat.Id magna exercitation reprehenderit aute exercitation adipisicing duis.Voluptate officia incididunt voluptate do cupidatat.Tempor sunt dolore sint ipsum dolor laborum ullamco esse tempor aute minim.Deserunt excepteur magna laboris veniam in quis.Cupidatat consequat elit anim voluptate deserunt consequat sunt.Reprehenderit ullamco consectetur exercitation voluptate ex pariatur esse in fugiat ea anim aute.Sint duis cupidatat adipisicing excepteur id veniam.Quis aute nulla voluptate consequat occaecat.Velit esse do ut magna proident cillum enim enim duis non ea.Cillum adipisicing culpa adipisicing amet ut sunt adipisicing elit anim laborum sit anim aliquip nostrud.Fugiat nulla cupidatat dolor ex pariatur laborum laboris do voluptate incididunt culpa deserunt.Id dolore adipisicing nisi et aliqua adipisicing.Magna voluptate laborum ad ex voluptate.Sit ullamco occaecat occaecat qui nostrud veniam nisi excepteur proident non.Ipsum tempor incididunt ipsum ea cillum consectetur laboris labore laboris excepteur.Dolor tempor in laboris commodo ea reprehenderit magna officia ut labore amet ad.Amet ipsum laboris nisi commodo nulla deserunt ut consequat.",
		Price:       2999000,
		Category:    "Router",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106076/lectronic/1678106075119276400.png",
		Stock:       3,
	},
	{
		Name:        "Beyerdynamic DT 990 Pro",
		Description: "The Beyerdynamic DT 990 Pro features open-back design, 250 ohm impedance, and a frequency response of 5 Hz - 35 kHz.Dolor in aute Lorem velit eu.Minim id consequat quis qui consectetur aliqua deserunt tempor consequat nostrud labore nisi.Magna ut aliqua labore in nulla.Aute nisi labore aliquip dolor.Deserunt et ea aliqua labore cillum ullamco non veniam occaecat nisi.Ut proident cillum nostrud velit sunt culpa culpa magna aute commodo cupidatat elit.Commodo tempor exercitation in nostrud est occaecat et fugiat consectetur sunt.Sit laborum velit irure deserunt ipsum in anim velit esse esse ea.Excepteur reprehenderit aute consectetur mollit do consequat ea nisi nulla deserunt adipisicing pariatur.Commodo in nisi elit ullamco pariatur adipisicing enim adipisicing sunt ut fugiat non aute eu.Deserunt occaecat laborum occaecat fugiat qui proident quis adipisicing proident nisi consectetur laboris.Anim officia officia ea laborum consectetur fugiat fugiat.Dolore consectetur adipisicing eiusmod voluptate.Nostrud ipsum sunt ipsum irure irure incididunt sunt nisi laboris.Aliqua sit sunt aliqua et adipisicing ut dolor culpa irure irure duis.",
		Price:       3699000,
		Category:    "Router",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106070/lectronic/1678106069252305300.png",
		Stock:       6,
	},
	{
		Name:        "Sennheiser HD 660 S",
		Description: "The Sennheiser HD 660 S features open-back design, 150 ohm impedance, and a frequency response of 10 Hz - 41 kHz.Mollit labore ad aute dolore est nisi in.Labore amet laborum ex ex incididunt sunt cupidatat adipisicing minim ad cillum exercitation.Consectetur eiusmod ipsum laborum anim cillum nulla labore cupidatat velit pariatur.Eu est reprehenderit ut dolor nostrud enim consequat esse.Eiusmod fugiat nulla officia magna.Anim in velit sunt consectetur cupidatat aliquip exercitation anim irure nostrud.Qui id exercitation consectetur nisi nisi.Aliqua ex cillum ea reprehenderit tempor duis sunt fugiat.Amet quis nulla sint et aute magna velit nulla.Excepteur est mollit deserunt cupidatat quis.In ipsum non non irure tempor aliquip qui id ex Lorem adipisicing.Ea ipsum tempor nulla deserunt exercitation nostrud excepteur exercitation.Sint sunt elit labore fugiat non fugiat nostrud adipisicing consectetur proident consequat.Laboris cupidatat quis anim mollit qui.Aliquip officia aliqua ex laborum deserunt nisi commodo sit ipsum ea.",
		Price:       7899000,
		Category:    "Handphone",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106063/lectronic/1678106062371155900.png",
		Stock:       3,
	},
	{
		Name:        "Audio-Technica ATH-M50x",
		Description: "The Audio-Technica ATH-M50x features closed-back design, 45mm drivers, and a frequency response of 15 Hz - 28 kHz.Laboris irure occaecat dolor sint consequat.Fugiat sit ex aliquip irure aliquip ut sint cillum qui amet fugiat.Id magna exercitation reprehenderit aute exercitation adipisicing duis.Voluptate officia incididunt voluptate do cupidatat.Tempor sunt dolore sint ipsum dolor laborum ullamco esse tempor aute minim.Deserunt excepteur magna laboris veniam in quis.Cupidatat consequat elit anim voluptate deserunt consequat sunt.Reprehenderit ullamco consectetur exercitation voluptate ex pariatur esse in fugiat ea anim aute.Sint duis cupidatat adipisicing excepteur id veniam.Quis aute nulla voluptate consequat occaecat.Velit esse do ut magna proident cillum enim enim duis non ea.Cillum adipisicing culpa adipisicing amet ut sunt adipisicing elit anim laborum sit anim aliquip nostrud.Fugiat nulla cupidatat dolor ex pariatur laborum laboris do voluptate incididunt culpa deserunt.Id dolore adipisicing nisi et aliqua adipisicing.Magna voluptate laborum ad ex voluptate.Sit ullamco occaecat occaecat qui nostrud veniam nisi excepteur proident non.Ipsum tempor incididunt ipsum ea cillum consectetur laboris labore laboris excepteur.Dolor tempor in laboris commodo ea reprehenderit magna officia ut labore amet ad.Amet ipsum laboris nisi commodo nulla deserunt ut consequat.",
		Price:       2999000,
		Category:    "Handphone",
		Image:       "https://res.cloudinary.com/duwd9m5ol/image/upload/v1678106076/lectronic/1678106075119276400.png",
		Stock:       3,
	},
}
